---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kf-pvc-operator
  namespace: kf-pvc-operator
rules:
# Framework: knowing which other operators are running (i.e. peering).
- apiGroups: [kopf.dev]
  resources: [clusterkopfpeerings]
  verbs: [list, watch, patch, get]
# Framework: runtime observation of namespaces & CRDs (addition/deletion).
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, watch]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list, watch, patch]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-pvc-operator
  namespace: kf-pvc-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kf-pvc-operator
  namespace: kf-pvc-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kf-pvc-operator
subjects:
- kind: ServiceAccount
  name: kf-pvc-operator
  namespace: kf-pvc-operator
